FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    python3-venv \
    git \
    wget \
    curl \
    libusb-1.0-0-dev \
    libudev-dev \
    joystick \
    procps \
    libportaudio2 \
    libportaudiocpp0 \
    portaudio19-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip setuptools wheel \
 && pip install -r requirements.txt

RUN cd ~ && git clone https://github.com/nduboi/Sound-Robocar.git && cd Sound-Robocar && pip install -r requirements.txt

#CMD ["python3", "gamepad_control.py"]
CMD ["/bin/bash"]
