FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    python3-venv \
    git \
    wget \
    curl \
    libusb-1.0-0-dev \
    libudev-dev \
    joystick \
    procps \
    libportaudio2 \
    libportaudiocpp0 \
    portaudio19-dev \
    xvfb \
    x11-utils \
    libsdl2-2.0-0 \
    libsdl2-image-2.0-0 \
    libsdl2-mixer-2.0-0 \
    libsdl2-ttf-2.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip setuptools wheel \
 && pip install -r requirements.txt

# Exposer les ports UDP pour communication réseau
EXPOSE 5000/udp 5001/udp

RUN cd ~ && git clone https://github.com/nduboi/Sound-Robocar.git && cd Sound-Robocar && pip install -r requirements.txt

# Par défaut, lancer le serveur (peut être overridé)
CMD ["python3", "server/robocar_server.py"]
