FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    python3-venv \
    git \
    wget \
    curl \
    libusb-1.0-0-dev \
    libudev-dev \
    joystick \
    procps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip setuptools wheel \
 && pip install -r requirements.txt

CMD ["/bin/bash"]
